sm6150-common: Revert PRODUCT_EXTRA_VNDK_VERSIONS
This fixes the following error:
14:46:03 Build sandboxing disabled due to nsjail error.
build/make/core/board_config.mk:525: 
error: VNDK version 29 not found.
14:46:03 dumpvars failed with: exit status 1